name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Prettier
        run: if [ "$(node_modules/.bin/prettier --list-different "**/*.js")" ]; then echo "Prettier failed" exit 1; fi

      - name: Unit-tests
        run: yarn test
